#!/usr/bin/env nix-shell
#!nix-shell -i bash -p curl gnused nix jq

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

# Beta releases are GitHub pre-releases, so /releases/latest won't work.
# Fetch recent releases and pick the first one that has ALL three assets we need:
#   brave-origin-beta_*_amd64.deb, brave-origin-v*-darwin-arm64.zip, brave-origin-v*-darwin-x64.zip
latestVersion="$(
  curl --fail -s ${GITHUB_TOKEN:+-u ":$GITHUB_TOKEN"} \
    "https://api.github.com/repos/brave/brave-browser/releases?per_page=30" \
  | jq -r '
      [ .[]
        | select(.prerelease == true)
        | select(
            (.assets | map(.name) | any(endswith("_amd64.deb") and startswith("brave-origin-beta")))
            and
            (.assets | map(.name) | any(endswith("-darwin-arm64.zip") and startswith("brave-origin-v")))
            and
            (.assets | map(.name) | any(endswith("-darwin-x64.zip") and startswith("brave-origin-v")))
          )
      ] | first | .tag_name
    ' \
  | sed 's/^v//'
)"

if [ -z "$latestVersion" ] || [ "$latestVersion" = "null" ]; then
  echo "ERROR: could not find a release with brave-origin-beta assets" >&2
  exit 1
fi

echo "Found Brave Origin Beta version: $latestVersion"

hashAmd64="$(nix-hash --to-sri --type sha256 "$(nix-prefetch-url --type sha256 "https://github.com/brave/brave-browser/releases/download/v${latestVersion}/brave-origin-beta_${latestVersion}_amd64.deb")")"
hashAarch64Darwin="$(nix-hash --to-sri --type sha256 "$(nix-prefetch-url --type sha256 "https://github.com/brave/brave-browser/releases/download/v${latestVersion}/brave-origin-v${latestVersion}-darwin-arm64.zip")")"
hashAmd64Darwin="$(nix-hash --to-sri --type sha256 "$(nix-prefetch-url --type sha256 "https://github.com/brave/brave-browser/releases/download/v${latestVersion}/brave-origin-v${latestVersion}-darwin-x64.zip")")"

cat > "$SCRIPT_DIR/default.nix" << EOF
# Expression generated by update.sh; do not edit it by hand!
{ stdenv, callPackage, ... }@args:

let
  pname = "brave-origin-beta";
  version = "${latestVersion}";

  allArchives = {
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v\${version}/brave-origin-beta_\${version}_amd64.deb";
      hash = "${hashAmd64}";
    };
    aarch64-darwin = {
      url = "https://github.com/brave/brave-browser/releases/download/v\${version}/brave-origin-v\${version}-darwin-arm64.zip";
      hash = "${hashAarch64Darwin}";
    };
    x86_64-darwin = {
      url = "https://github.com/brave/brave-browser/releases/download/v\${version}/brave-origin-v\${version}-darwin-x64.zip";
      hash = "${hashAmd64Darwin}";
    };
  };

  archive =
    if builtins.hasAttr stdenv.system allArchives then
      allArchives.\${stdenv.system}
    else
      throw "Unsupported platform.";

in
callPackage ./make-brave-origin-beta.nix (removeAttrs args [ "callPackage" ]) (
  archive
  // {
    inherit pname version;
  }
)
EOF

echo "Updated default.nix to version $latestVersion"
