# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/" = {
      device = "/dev/mapper/luks-57594530-d51d-466c-98ae-b046c1413d0b";
      fsType = "btrfs";
      options = [
        "compress=zstd:3"
        "discard=async"
        "noatime"
      ];
    };
    "/nix" = {
      device = "/dev/mapper/luks-57594530-d51d-466c-98ae-b046c1413d0b";
      fsType = "btrfs";
      options = [
        "subvol=nix"
        "compress=zstd:3"
        "discard=async"
        "noatime"
      ];
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/EBF9-102F";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };
    "/home" = {
      device = "/dev/mapper/luks-a4364608-7adf-474b-89c9-47a5e1d07deb";
      fsType = "btrfs";
      options = [
        "compress=zstd:3"
        "discard=async"
        "noatime"
      ];
    };
  };

  boot.initrd.luks.devices = {
    "luks-57594530-d51d-466c-98ae-b046c1413d0b" = {
      device = "/dev/disk/by-uuid/57594530-d51d-466c-98ae-b046c1413d0b";
      allowDiscards = true;
    };
    "luks-a4364608-7adf-474b-89c9-47a5e1d07deb" = {
      device = "/dev/disk/by-uuid/a4364608-7adf-474b-89c9-47a5e1d07deb";
      allowDiscards = true;
    };
  };

  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 50;
    priority = 100;
  };
  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 32 * 1024;
      priority = 0;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp39s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp41s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
